#pragma once

typedef enum {
    INT, STRING, BOOL, DOUBLE,

    LEFT_PAREN, RIGHT_PAREN, VALUE,

    TRUE, FALSE, LITERAL, INT_TYPE, DOUBLE_TYPE,

    ADD_COLUMN, ADD_ROW, GET_ELEMENT, REMOVE_COLUMN, REMOVE_ROW, EDIT_ROW, EDIT_ELEMENT, EDIT_COLNAME,

    END_OF_TEXT,
} TokenType;