#pragma once

typedef enum {
    INT, STRING, BOOL, DOUBLE,

    LEFT_PAREN, RIGHT_PAREN, VALUE,

    TRUE, FALSE, LITERAL,

    ADD_COLUMN, ADD_ROW, GET_ELEMENT, REMOVE_COLUMN, REMOVE_ROW,

    END_OF_TEXT,
} TokenType;